version: '3.1'

services:
  db:
    image: mongo:8.0.4
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    networks:
      - app-network

  api-server:
    build: ./api-server
    container_name: api-server
    depends_on:
      - db
    ports:
      - '443:443'
    networks:
      - app-network

  analysis:
    build: ./analysis
    container_name: analysis
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
