services:
  db:
    image: mongo:8.0.4
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db # added volume mapping for persisting data
    networks:
      - app-network
    logging:
      driver: 'json-file'
      options:
        max-size: '20k'
        max-file: '3'

  api-server:
    build: ./api-server
    container_name: api-server
    depends_on:
      - db
    ports:
      - '80:80'
    volumes:
      - ./audio_files:/app/audio_files # Add this line to mount the local directory
    networks:
      - app-network
    environment:
      # Use the host "mongodb" to connect to the internal MongoDB container
      MONGO_URI: 'mongodb:27017'
      MONGO_DBNAME: 'observationdb'
      MONGO_USERNAME: 'root'
      MONGO_PASSWORD: 'root'
    logging:
      driver: 'json-file'
      options:
        max-size: '20k'
        max-file: '3'

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: # added persistent volume declaration
