services:
  db:
    image: mongo:8.0.4
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    networks:
      - app-network
    logging:
      driver: 'json-file'
      options:
        max-size: '1k'
        max-file: '3'

  api-server:
    build: ./api-server
    container_name: api-server
    depends_on:
      - db
    ports:
      - '443:443'
    networks:
      - app-network
    logging:
      driver: 'json-file'
      options:
        max-size: '1k'
        max-file: '3'

  analysis:
    build: ./analysis
    container_name: analysis
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - type: bind
        source: /data
        target: /data
    logging:
      driver: 'json-file'
      options:
        max-size: '1k'
        max-file: '3'

networks:
  app-network:
    driver: bridge
